vich_uploader:
    db_driver: orm

    mappings:
        blog:
            uri_prefix: "%app.path.blog_images%"
            upload_destination: '%kernel.project_dir%/public%app.path.blog_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        products:
            uri_prefix: "%app.path.product_images%"
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
