<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOVBdykk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOVBdykk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOVBdykk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOVBdykk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOVBdykk\App_KernelDevDebugContainer([
    'container.build_hash' => 'OVBdykk',
    'container.build_id' => 'd900dadb',
    'container.build_time' => 1744395810,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOVBdykk');
