<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQusFEAY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQusFEAY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQusFEAY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQusFEAY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQusFEAY\App_KernelDevDebugContainer([
    'container.build_hash' => 'QusFEAY',
    'container.build_id' => '43588bd2',
    'container.build_time' => 1744935051,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQusFEAY');
