<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZltzx67\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZltzx67/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZltzx67.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZltzx67\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZltzx67\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zltzx67',
    'container.build_id' => 'e4074b47',
    'container.build_time' => 1745498736,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZltzx67');
